name: Deploy CA

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        
      config_version:
        required: true
        type: string     

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }} 

    permissions:
      contents: write
      actions: write
  
    steps:
      - uses: actions/checkout@v4

      - name: Download eda chart
        run: |
          echo "Downloading chart"

      - name: Available Images to deploy
        run: |
          echo "Config Image: config:${{ inputs.config_version }}"
        
