name: Build EDA CA Config

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }} 

    permissions:
      contents: write
      actions: write
  
    steps:
      - uses: actions/checkout@v4

      - name: Print imputs
        run: |
          echo "environment_name: ${{ inputs.environment }}"
          echo "curr_ver_variable_name: CONFIG_CURR_VERSION "
          echo "prev_ver_variable_name: CONFIG_PREV_VERSION "       
          echo "current_value: ${{ vars.CONFIG_CURR_VERSION  }}"
          echo "previous_value: ${{ vars.CONFIG_PREV_VERSION  }}"

      - name: Increment Version
        id: version_step
        uses: ./.github/actions/update-version
        with:
          environment_name: ${{ inputs.environment }}
          curr_ver_variable_name: CONFIG_CURR_VERSION 
          curr_ver_value: ${{ vars.CONFIG_CURR_VERSION  }}
          prev_ver_variable_name: CONFIG_PREV_VERSION 
          prev_ver_value: ${{ vars.CONFIG_PREV_VERSION  }}
          github_token: ${{ secrets.GH_ADMIN_TOKEN }}
          

      - name: Print version
        run: |
          echo "NEW VERSION: ${{ steps.version_step.outputs.version }}"
          echo "OLD VERSION: ${{ steps.version_step.outputs.old_version }}"
