name: Main Workflow 

on:
  push:
    branches:
      - master
  workflow_dispatch: # This enables the manual trigger button
    inputs:
      environmnet:
        description: 'dev|stg|prod'
        required: true
        default: 'dev'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  build-eda-config:
    needs: build
    uses: ./.github/workflows/eda-config.yml
    with:
      environment: dev
